version: "3.9"

services:
  db:
    image: docker.io/postgres:15
    container_name: parking_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parking_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: docs/Dockerfile
    container_name: parking_backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src/app.py
    depends_on:
      - db

volumes:
  pgdata:
